version: '3.9'

services:
  database:
    image: mysql:latest
    container_name: db-jelou
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}    
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./database-mysql:/var/lib/mysql"
  api-server:
    build:
      context: ./projects/backend-jelou
      dockerfile: Dockerfile
    env_file: .env
    container_name: ${PROJECT_NAME}-${JOB_BASE_NAME}
    image: server/${PROJECT_NAME}
    ports:
      - "${PORT_LOCAL}:${PORT_LOCAL}"
    volumes:
      - ./projects/backend-jelou/:/app
      - /app/node_modules
      - /app/src/auths/certs
    depends_on:
      - database   
